// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditTodo struct {
	ID       string  `json:"id"`
	Name     *string `json:"name,omitempty"`
	IsActive *bool   `json:"isActive,omitempty"`
}

type NewTodo struct {
	Name string `json:"name"`
}

type Todo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	IsActive    bool   `json:"isActive"`
	DateCreated string `json:"dateCreated"`
}
